#!/bin/bash

###############################################################################
# Bob + IBM ICA - Automated PR Creation Script
# This script demonstrates how Bob creates a PR that triggers IBM ICA validation
###############################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
REPO_NAME="calculator-project"
BASE_BRANCH="main"
IBM_ICA_API="${IBM_ICA_API_URL:-https://ica.ibm.com/api/v1}"

###############################################################################
# Functions
###############################################################################

print_header() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}ℹ️  $1${NC}"
}

###############################################################################
# Main Script
###############################################################################

print_header "Bob + IBM ICA - PR Creation POC"

# Step 1: Get user prompt
echo ""
print_info "Step 1: What code would you like Bob to generate?"
read -p "Enter your prompt: " USER_PROMPT

if [ -z "$USER_PROMPT" ]; then
    print_error "Prompt cannot be empty"
    exit 1
fi

print_success "Prompt received: $USER_PROMPT"

# Step 2: Generate feature name from prompt
FEATURE_NAME=$(echo "$USER_PROMPT" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed 's/[^a-z0-9-]//g')
BRANCH_NAME="bob-generated-${FEATURE_NAME}"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)

print_info "Generated branch name: $BRANCH_NAME"

# Step 3: Create new branch
echo ""
print_info "Step 2: Creating new branch..."
git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"
print_success "Branch created: $BRANCH_NAME"

# Step 4: Simulate Bob generating code
echo ""
print_info "Step 3: Bob is generating code..."
sleep 2  # Simulate code generation time

# Create a sample file to demonstrate
cat > "../bob-generated-${TIMESTAMP}.txt" << EOF
# Bob Generated Code
Timestamp: $(date)
Prompt: $USER_PROMPT
Branch: $BRANCH_NAME

This file represents code generated by Bob AI Assistant.
In a real scenario, Bob would generate actual Java code based on your prompt.

Example changes that Bob might make:
- Add new calculator functions
- Improve error handling
- Add unit tests
- Update documentation
EOF

print_success "Code generated successfully"

# Step 5: Stage and commit changes
echo ""
print_info "Step 4: Committing changes..."
git add .
git commit -m "🤖 Bob Generated: $USER_PROMPT

Generated by: Bob AI Assistant
Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)
Branch: $BRANCH_NAME

This commit contains AI-generated code that will be validated by IBM ICA.
"
print_success "Changes committed"

# Step 6: Push to remote
echo ""
print_info "Step 5: Pushing to remote repository..."
git push -u origin "$BRANCH_NAME"
print_success "Branch pushed to remote"

# Step 7: Create PR via GitHub API
echo ""
print_info "Step 6: Creating Pull Request..."

PR_TITLE="[Bob Generated] $USER_PROMPT"
PR_BODY="## 🤖 AI-Generated Code by Bob

**Generated on:** $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Prompt:** $USER_PROMPT

### Changes Made:
- Generated code based on user prompt
- Ready for IBM ICA validation

### Files Modified:
\`\`\`
$(git diff --name-only $BASE_BRANCH..$BRANCH_NAME)
\`\`\`

---
**⚠️ This PR is auto-generated and will be validated by IBM ICA**

### Validation Status:
- [ ] Code Quality Check
- [ ] Unit Tests
- [ ] Security Scan
- [ ] Build Verification

IBM ICA will automatically approve or reject this PR based on validation results.
"

# Create PR using GitHub CLI (if available)
if command -v gh &> /dev/null; then
    PR_URL=$(gh pr create \
        --title "$PR_TITLE" \
        --body "$PR_BODY" \
        --base "$BASE_BRANCH" \
        --head "$BRANCH_NAME" \
        --label "bob-generated,automated-pr,needs-validation" \
        --draft)
    
    print_success "Pull Request created: $PR_URL"
else
    print_info "GitHub CLI not found. Please create PR manually or install 'gh' CLI"
    print_info "PR Title: $PR_TITLE"
    print_info "PR Branch: $BRANCH_NAME -> $BASE_BRANCH"
fi

# Step 8: Notify IBM ICA
echo ""
print_info "Step 7: Notifying IBM ICA..."

if [ -n "$IBM_CLOUD_API_KEY" ]; then
    curl -X POST "$IBM_ICA_API/pr-workflow/trigger" \
        -H "Authorization: Bearer $IBM_CLOUD_API_KEY" \
        -H "Content-Type: application/json" \
        -d "{
            \"repository\": \"$REPO_NAME\",
            \"branch\": \"$BRANCH_NAME\",
            \"base_branch\": \"$BASE_BRANCH\",
            \"prompt\": \"$USER_PROMPT\",
            \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
            \"generated_by\": \"bob-ai\"
        }" \
        --silent --show-error
    
    print_success "IBM ICA notified"
else
    print_info "IBM_CLOUD_API_KEY not set. Skipping IBM ICA notification."
fi

# Step 9: Summary
echo ""
print_header "Summary"
echo ""
echo "Branch:        $BRANCH_NAME"
echo "PR Title:      $PR_TITLE"
echo "Base Branch:   $BASE_BRANCH"
echo ""
print_info "IBM ICA will now:"
echo "  1. Run code quality checks (SonarQube, Checkstyle)"
echo "  2. Build the project (Maven)"
echo "  3. Run unit tests (JUnit)"
echo "  4. Perform security scan (Snyk, OWASP)"
echo "  5. Auto-approve if all checks pass"
echo "  6. Auto-reject if any check fails"
echo ""
print_info "Expected validation time: 2-5 minutes"
echo ""
print_success "POC demonstration complete!"
echo ""
print_info "Monitor the PR for validation results and auto-approval/rejection."

# Step 10: Watch PR status (optional)
echo ""
read -p "Would you like to watch the PR status? (y/n): " WATCH_PR

if [ "$WATCH_PR" = "y" ] || [ "$WATCH_PR" = "Y" ]; then
    print_info "Watching PR status... (Press Ctrl+C to stop)"
    echo ""
    
    while true; do
        if command -v gh &> /dev/null; then
            gh pr view "$BRANCH_NAME" --json state,statusCheckRollup,reviews \
                --template '
Status: {{.state}}
Checks: {{range .statusCheckRollup}}
  - {{.context}}: {{.state}}{{end}}
Reviews: {{range .reviews}}
  - {{.author.login}}: {{.state}}{{end}}
'
        fi
        sleep 30
    done
fi

# Made with Bob
